"""Criação de tabelas de entradas e saídas

Revision ID: 2840d2b3348a
Revises: c6491ef4a248
Create Date: 2025-02-24 17:17:54.128296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2840d2b3348a'
down_revision: Union[str, None] = 'c6491ef4a248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
