"""Criação de tabelas de entradas e saídas

Revision ID: 9ad314c3665e
Revises: 2840d2b3348a
Create Date: 2025-02-24 18:17:08.752842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad314c3665e'
down_revision: Union[str, None] = '2840d2b3348a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
