"""Criação de tabelas de entradas e saídas

Revision ID: c6491ef4a248
Revises: 707a46498f1e
Create Date: 2025-02-24 17:06:39.042341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6491ef4a248'
down_revision: Union[str, None] = '707a46498f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas',
    sa.Column('idEntrada', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('dizimos', 'ofertas', 'ofertas_missionarias', 'campanhas', 'eventos', 'venda_materiais', 'doacoes_empresas', 'parcerias_ongs', 'apoio_outras_igrejas', 'investimentos', name='tipoentrada'), nullable=False),
    sa.Column('dataRegistro', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idEntrada')
    )
    op.create_index(op.f('ix_entradas_idEntrada'), 'entradas', ['idEntrada'], unique=False)
    op.create_table('saidas',
    sa.Column('idSaida', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('folha_pagamento', 'encargos_sociais', 'aluguel_imovel', 'manutencao_templo', 'contas_mensais', 'compra_materiais', 'ajuda_social', 'eventos_congressos', 'missoes_evangelismo', 'taxas_impostos', 'marketing_divulgacao', 'instrumentos_musicais', 'despesas_viagens', 'seguranca', 'ofertas_pastores', name='tiposaida'), nullable=False),
    sa.Column('dataRegistro', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idSaida')
    )
    op.create_index(op.f('ix_saidas_idSaida'), 'saidas', ['idSaida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saidas_idSaida'), table_name='saidas')
    op.drop_table('saidas')
    op.drop_index(op.f('ix_entradas_idEntrada'), table_name='entradas')
    op.drop_table('entradas')
    # ### end Alembic commands ###
